### ISSUE TITLE
New GPSR Commands

### ISSUE THREAD

**Issue by johaq** [kyordhel/GPSRCmdGen2015#10]
Hi,
I noticed that the download for the current Rulebook only includes the SPR Test. Does that mean for upcoming events (ie German Open) we should stick to the old generator? Or can we expect a new version soon?

Best regards,
Johannes

**Comment by kyordhel** [comment]
Johannes,

You can expect a new version soon. The generators themselves most likely won't change but grammars will be updated.

Cheers!

**Comment by kyordhel** [comment]
Done long time ago. Why I didn't close this issue?
