### ISSUE TITLE
Anaphoric references

### ISSUE THREAD

**Issue by arturo8602** [kyordhel/GPSRCmdGen2015#12]
In the examples of the questions of the SPR test, there are questions with mention to a previous question, for example:

Section A.4. Object Questions:
7. What objects are in the closet? ->The shampoo, soap, the sponge and a cloth.
8. How many are they? ->There are four objects in the closet.
9. Do they belong to the same category? -> They are all cleaning stuff

But in the command generator there are no questions with mentions to previous questions.
It should be convenient adding this kind of questions. 

Arturo Rodríguez, Team Golem

**Comment by kyordhel** [comment]
You are right, but I need help and add environmental reasoning to the generator.
Maybe for next year.
