### ISSUE TITLE
Add pronouns

### ISSUE THREAD

**Issue by kyordhel** [kyordhel/GPSRCmdGen2015#14]
Referring people with *them* is not a good approach. The generator should incorporate some primitives to refer to previously mentioned people/objects.

This refers to #11

**Comment by fpolster** [comment]
Referring people with it could also be misinterpreted..

e.g. from EEGPSR cat 8:  "Please locate Noah in the Bar, guide it to the exit, and find Ava in the Bed."

**Comment by kyordhel** [comment]
Is buggy but more or less working now.
