### ISSUE TITLE
Update the README please

### ISSUE THREAD

**Issue by thetaleofnarutouzumaki** [kyordhel/GPSRCmdGen2015#18]
Ola, 
could you update the README please, the following command is not seem to work as there is no **Release** folder. 

command: **mono bin/Release/GPSRCmdGen.exe**

Obrigado :+1: 

Mithun K.

**Comment by kyordhel** [comment]
It should work if you compile it first.

You closed the issue, does that mean the problem is solved or should I dig into it?

**Comment by thetaleofnarutouzumaki** [comment]
Sorry sorry, my mistake. It's good, I didn't compile it before. 
thank you :+1:
