### ISSUE TITLE
What to do after "finding"

### ISSUE THREAD

**Issue by LoyVanBeek** [kyordhel/GPSRCmdGen2015#4]
Commands like "navigate to the bathroom and find the orange juice" should be more specific in what to do after "finding". 
The robot should indicate that is has found the item and the TC should make sure it has, somehow. 
Or let the robot point at the item or go to it. 

If not, the robot can see "I found it" after one look around and we have no way to check this.

**Comment by kyordhel** [comment]
Indeed, that command is incomplete. A deliver|bring it to {placement} is missing, or at least a "grasp|point to it"

Before fixing that problem (can be easily donde just by updating the grammar files), I would like to fix problem certain bugs in the rulebook.

Most probably, all grammars need to be rewritten.

https://github.com/RoboCupAtHome/RuleBook/issues/40
